#%RAML 0.8
title: IOTOS Application Framework
version: v0.1
mediaType: application/json
schemas:
  - Apps: !include application.json

/apps:
  description: |
    Interface for Application Framework management

  get:
    description: |
      List all running applications

  post:
    description: |
      Start all installed applications

  delete:
    description: |
      Stop all running applications

  put:
    description: |
      Restart all running applications

  /{appId}:
    description: |
      Interface for single application

    get:
      description: |
        List single running application

    post:
      description: |
        Start single application

    delete:
      description: |
        Stop single running application

    put:
      description: |
        Restart single running application

/install:
  description: |
    Interface for Application Framework install/uninstall

  get:
    description: |
      List all installed applications

  post:
    description: |
      Update all installed applications

  delete:
    description: |
      Uninstall all installed applications

  put:
    description: |
      Reinstall all installed applications

  /{appId}:
    description: |
      Interface for single application install/uninstall

    get:
      description: |
        List single installed application

    post:
      description: |
        Update single application

    delete:
      description: |
        Uninstall single installed application

    put:
      description: |
        Reinstall single installed application
